flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:ewestern/haskell-postgis.git
    commit: 04f615fe994d9c53ea7dc7fce305fc82c5e4d7b0
  extra-dep: true

resolver: lts-8.13
