flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:ewestern/haskell-postgis.git
    commit: d42ad9bdac2d714e2f9231385d3fb4d0fb3e0e5f
  extra-dep: true

resolver: lts-8.13
